# 課題003 NumPyで配列の操作や演算をしよう

2つの行列 A（3行2列）と B（2行4列）の積を NumPy で計算し、結果と要素の最大値を表示する。

```
A = [[0, 1],        B = [[0, 1, 2, 3],
     [2, 3],             [4, 5, 6, 7]]
     [4, 5]]

     3行2列                 2行4列
```

## 合格基準との対応

| 番号 | 合格基準 | このコードでの該当箇所 |
|---|---|---|
| 1 | NumPyをインポートできていること | `import numpy as np`（Step1） |
| 2 | 多次元配列のコードが記述できていること | `np.array([[...], [...]])` で A・B を2次元配列として定義（Step2） |
| 3 | 行列演算ができていること | `A @ B` で行列の積を計算（Step3・Step4） |
| 4 | 最大値を求めるコードが記述できていること | `C.max()`（Step5） |

## 設計のポイント

- **行と列を入れ違えない**：`np.array` に渡すリストは「外側のリストが行、内側の要素が列」。
  行ごとに改行して書き、`shape` も表示して A が (3, 2)、B が (2, 4) であることを確認している。
- **積が計算できる条件**：左の行列の列数と右の行列の行数が一致している必要がある。
  ここは A の列数 2 と B の行数 2 が一致するので計算でき、結果は 3行4列になる。
- **`*` ではなく `@`**：NumPy の `*` は要素ごとの積（アダマール積）になってしまうため、
  行列の積には `@` を使う（`np.dot(A, B)` や `A.dot(B)` でも同じ結果）。

In [1]:
# Step1. NumPyをインポートする
import numpy as np

# Step2. AとBの行列を多次元配列で用意する
# 外側のリストが「行」、内側の要素が「列」。Aは3行2列、Bは2行4列になる
A = np.array([[0, 1],
              [2, 3],
              [4, 5]])

B = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])

# 行と列を入れ違えていないか、形状を表示して確認する
print("Aの形状:", A.shape)
print("Bの形状:", B.shape)

# Step3. 行列の積を計算する
# Aの列数(2)とBの行数(2)が一致しているので計算できる。結果は3行4列になる
# 「*」は要素ごとの積になってしまうので、行列の積には「@」を使う
C = A @ B

# Step4. 計算結果を表示する
print("行列の積 A×B:")
print(C)
print("A×Bの形状:", C.shape)

# Step5. 行列の要素の最大値を求めて表示する
print("最大値:", C.max())

Aの形状: (3, 2)
Bの形状: (2, 4)
行列の積 A×B:
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
A×Bの形状: (3, 4)
最大値: 47
